/*
 * HelloApiSchema
 *
 * Practice api schema
 *
 * API version: 1.0.0
 * Contact: doriven@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	"github.com/GIT_USER_ID/GIT_REPO_ID/pkg/api"
	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/pkg/openapi"
	"github.com/gorilla/handlers"
)

func main() {
	log.Printf("Server started")

	mockApiService := api.NewMockApiService()
	mockApiController := openapi.NewDefaultApiController(mockApiService)

	router := openapi.NewRouter(mockApiController)

	log.Fatal(http.ListenAndServe(":8080", handlers.CORS(
		handlers.AllowedMethods([]string{"GET", "PUT", "POST", "DELETE"}),
		handlers.AllowedHeaders([]string{"Content-Type"}),
	)(router)))
}
