/*
 * HelloApiSchema
 *
 * Practice api schema
 *
 * API version: 1.0.0
 * Contact: doriven@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UpdateUserInput struct {

	Id int64 `json:"id"`

	EmailAddress string `json:"email_address,omitempty"`

	LastName string `json:"last_name,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	Birthday string `json:"birthday,omitempty"`

	Address string `json:"address,omitempty"`
}
