/*
 * HelloApiSchema
 *
 * Practice api schema
 *
 * API version: 1.0.0
 * Contact: doriven@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UpdateUserOutput struct {

	Id int64 `json:"id"`

	EmailAddress string `json:"email_address"`

	LastName string `json:"last_name"`

	FirstName string `json:"first_name"`

	Birthday string `json:"birthday"`

	Address string `json:"address"`
}
