/* tslint:disable */
/* eslint-disable */
/**
 * HelloApiSchema
 * Practice api schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: doriven@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateUserInput,
    CreateUserInputFromJSON,
    CreateUserInputToJSON,
    CreateUserOutput,
    CreateUserOutputFromJSON,
    CreateUserOutputToJSON,
    GetUserOutput,
    GetUserOutputFromJSON,
    GetUserOutputToJSON,
    UpdateUserInput,
    UpdateUserInputFromJSON,
    UpdateUserInputToJSON,
    UpdateUserOutput,
    UpdateUserOutputFromJSON,
    UpdateUserOutputToJSON,
} from '../models';

export interface CreateUserRequest {
    createUserInput: CreateUserInput;
}

export interface GetUserRequest {
    id: number;
}

export interface UpdateUserRequest {
    updateUserInput: UpdateUserInput;
}

/**
 * no description
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Create a new user.
     */
    async createUserRaw(requestParameters: CreateUserRequest): Promise<runtime.ApiResponse<CreateUserOutput>> {
        if (requestParameters.createUserInput === null || requestParameters.createUserInput === undefined) {
            throw new runtime.RequiredError('createUserInput','Required parameter requestParameters.createUserInput was null or undefined when calling createUser.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application:json';

        const response = await this.request({
            path: `/users`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserInputToJSON(requestParameters.createUserInput),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateUserOutputFromJSON(jsonValue));
    }

    /**
     * Create a new user.
     */
    async createUser(requestParameters: CreateUserRequest): Promise<CreateUserOutput> {
        const response = await this.createUserRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get a user by id.
     */
    async getUserRaw(requestParameters: GetUserRequest): Promise<runtime.ApiResponse<GetUserOutput>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getUser.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserOutputFromJSON(jsonValue));
    }

    /**
     * Get a user by id.
     */
    async getUser(requestParameters: GetUserRequest): Promise<GetUserOutput> {
        const response = await this.getUserRaw(requestParameters);
        return await response.value();
    }

    /**
     * Update a user.
     */
    async updateUserRaw(requestParameters: UpdateUserRequest): Promise<runtime.ApiResponse<UpdateUserOutput>> {
        if (requestParameters.updateUserInput === null || requestParameters.updateUserInput === undefined) {
            throw new runtime.RequiredError('updateUserInput','Required parameter requestParameters.updateUserInput was null or undefined when calling updateUser.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application:json';

        const response = await this.request({
            path: `/users`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserInputToJSON(requestParameters.updateUserInput),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateUserOutputFromJSON(jsonValue));
    }

    /**
     * Update a user.
     */
    async updateUser(requestParameters: UpdateUserRequest): Promise<UpdateUserOutput> {
        const response = await this.updateUserRaw(requestParameters);
        return await response.value();
    }

}
